SHOW DATABASES;

CREATE DATABASE EMP_DP;

USE EMP_DP;

CREATE TABLE EMP_DETAILS(
    E_ID INT,
    E_NAME VARCHAR(20),
    E_DEPT VARCHAR(25),
    E_JOINDATE DATE,
    E_SALARY INT
);

SELECT * FROM EMP_DETAILS;

ALTER TABLE EMP_DETAILS
ADD PH_NUMBER VARCHAR(10);

ALTER TABLE EMP_DETAILS
RENAME COLUMN PH_NUMBER TO PH_NO;

ALTER TABLE EMP_DETAILS
MODIFY COLUMN PH_NO VARCHAR(12);

ALTER TABLE EMP_DETAILS
ADD EMAIL VARCHAR(50);

ALTER TABLE EMP_DETAILS
MODIFY COLUMN EMAIL VARCHAR(50)
AFTER E_SALARY;

SELECT * FROM EMP_DETAILS;

ALTER TABLE EMP_DETAILS
MODIFY COLUMN EMAIL VARCHAR(50)
FIRST;

ALTER TABLE EMP_DETAILS
DROP COLUMN EMAIL;

INSERT INTO EMP_DETAILS(E_ID,E_NAME,E_DEPT,E_JOINDATE,E_SALARY,PH_NO)
VALUES (101,"KAVIYA","IT","2025-02-15",20000,"1234567890");

INSERT INTO EMP_DETAILS
VALUES (102,"PRIYA","DS","2025-05-20",25000,"1234567891");

INSERT INTO EMP_DETAILS(E_ID,E_NAME,E_SALARY)
VALUES (103,"SURYA",30000);

INSERT INTO EMP_DETAILS(E_ID,E_NAME,E_DEPT,PH_NO)
VALUES (104,"KUMAR","CS","1234567894");

INSERT INTO EMP_DETAILS
VALUES (105,"ARUN","IT","2025-06-10",35000,"1234567895");

INSERT INTO EMP_DETAILS
VALUES (106,"SNEHA","HR","2025-06-12",28000,"1234567896");

INSERT INTO EMP_DETAILS
VALUES (107,"RAHUL","DS","2025-06-15",40000,"1234567897");

INSERT INTO EMP_DETAILS
VALUES (108,"MEENA","IT","2025-06-18",32000,"1234567898");

SELECT * FROM EMP_DETAILS;

SELECT E_ID,E_NAME,E_DEPT
FROM EMP_DETAILS;

SELECT
E_ID AS ID,
E_NAME AS ENAME,
E_DEPT AS DEPT
FROM EMP_DETAILS;

SELECT *
FROM EMP_DETAILS
WHERE E_DEPT = "IT";

SELECT *
FROM EMP_DETAILS
WHERE E_SALARY > 30000;


SELECT *
FROM EMP_DETAILS
WHERE E_NAME LIKE "K%";

SELECT *
FROM EMP_DETAILS
ORDER BY E_SALARY ASC;

SELECT *
FROM EMP_DETAILS
ORDER BY E_SALARY DESC;

SELECT MAX(E_SALARY) AS MAX_SALARY
FROM EMP_DETAILS;

SELECT MIN(E_SALARY) AS MIN_SALARY
FROM EMP_DETAILS;

SELECT AVG(E_SALARY) AS AVG_SALARY
FROM EMP_DETAILS;

SELECT SUM(E_SALARY) AS TOTAL_SALARY
FROM EMP_DETAILS;

SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMP_DETAILS;

SELECT
E_DEPT,
SUM(E_SALARY) AS TOTAL_SALARY
FROM EMP_DETAILS
GROUP BY E_DEPT;

SELECT
E_DEPT,
COUNT(*) AS EMP_COUNT
FROM EMP_DETAILS
GROUP BY E_DEPT;

CREATE TABLE DEPARTMENT(
    D_ID INT PRIMARY KEY,
    D_NAME VARCHAR(30),
    LOCATION VARCHAR(30)
);

INSERT INTO DEPARTMENT
VALUES
(1,"IT","CHENNAI"),
(2,"HR","BANGALORE"),
(3,"DS","HYDERABAD"),
(4,"CS","MUMBAI");

ALTER TABLE EMP_DETAILS
ADD D_ID INT;

SET SQL_SAFE_UPDATES = 0;

UPDATE EMP_DETAILS
SET D_ID = 1
WHERE E_DEPT = "IT";

UPDATE EMP_DETAILS
SET D_ID = 2
WHERE E_DEPT = "HR";

UPDATE EMP_DETAILS
SET D_ID = 3
WHERE E_DEPT = "DS";

UPDATE EMP_DETAILS
SET D_ID = 4
WHERE E_DEPT = "CS";

SELECT
EMP_DETAILS.E_NAME,
EMP_DETAILS.E_DEPT,
DEPARTMENT.LOCATION
FROM EMP_DETAILS
INNER JOIN DEPARTMENT
ON EMP_DETAILS.D_ID = DEPARTMENT.D_ID;

SELECT
EMP_DETAILS.E_NAME,
DEPARTMENT.LOCATION
FROM EMP_DETAILS
LEFT JOIN DEPARTMENT
ON EMP_DETAILS.D_ID = DEPARTMENT.D_ID;

SELECT
EMP_DETAILS.E_NAME,
DEPARTMENT.LOCATION
FROM EMP_DETAILS
RIGHT JOIN DEPARTMENT
ON EMP_DETAILS.D_ID = DEPARTMENT.D_ID;


CREATE TABLE OLD_EMPLOYEE(
    E_ID INT,
    E_NAME VARCHAR(20)
);

INSERT INTO OLD_EMPLOYEE
VALUES
(201,"RAM"),
(202,"ANU");

SELECT E_ID,E_NAME
FROM EMP_DETAILS

UNION

SELECT E_ID,E_NAME
FROM OLD_EMPLOYEE;

UPDATE EMP_DETAILS
SET E_SALARY = 50000
WHERE E_ID = 101;

DELETE FROM EMP_DETAILS
WHERE E_ID = 104;

CREATE VIEW EMP_VIEW AS
SELECT
E_ID,
E_NAME,
E_DEPT,
E_SALARY
FROM EMP_DETAILS;

SELECT * FROM EMP_VIEW;

CREATE TABLE EMPLOYEE(
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(30) NOT NULL,
    EMP_DEPT VARCHAR(20),
    EMP_SALARY INT CHECK (EMP_SALARY > 10000)
);

INSERT INTO EMPLOYEE
VALUES (1,"ARUN","IT",25000);

INSERT INTO EMPLOYEE
VALUES (2,"PRIYA","HR",30000);

SELECT * FROM EMPLOYEE;

DELIMITER //

CREATE PROCEDURE GET_EMPLOYEE()
BEGIN
    SELECT * FROM EMP_DETAILS;
END //

DELIMITER ;

CALL GET_EMPLOYEE();

SELECT * FROM EMP_DETAILS;